language: csharp

dotnet: 2.1.4
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - dotnet build TP_lb3_Mass.sln -c 
    - dotnet test -c Release --no-build UnitTestProject1/UnitTestProject1.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
        - bash <(curl -s https://codecov.io/bash)
