language: csharp  
sudo: required 
solution: "./TP_lb3_Mass.sln"
mono: none
dotnet: 2.0.0

install:
- dotnet restore
dist: trusty  
script:
 - dotnet build
 - dotnet test MTAServiceStatus.Tests/MTAServiceStatus.Tests.csproj
