language: csharp
solution: "./TP_lb3_Mass.sln"
os: windows
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./TP_lb3_Mass.sln
script:
- xbuild ./TP_lb3_Mass.sln
- mono ./ClassOperTests/packages/xunit.runner.console*/tools/xunit.console.exe ./ClassOperTests/bin/Debug/ClassOperTests.dll
