language: csharp
solution: Laba_TP_1_1.sln
sudo: required  
mono: none
dist: trusty  
 matrix:
 - TARGET=cs
script:  
 - cd $TRAVIS_BUILD_DIR
  # build the target. This will call haxe with the HXFLAGS and HXFLAGS_EXTRA environment variables
- HXFLAGS="-cp src -main test.TestAll" ~/travis-hx/build.sh

